require 'android_lint_translate_checkstyle_format/version'
require 'android_lint_translate_checkstyle_format/translate'
require 'android_lint_translate_checkstyle_format/script'

module AndroidLintTranslateCheckstyleFormat
end
